### ISSUE TITLE
possible lossy conversion from int to with compound statements

### ISSUE THREAD

**Issue by ggitmike** [manifold-systems/manifold#231]
When enabling the manifold preprocessor plugin using
"    compileOnly group: 'systems.manifold', name: 'manifold-preprocessor', version: '2020.1.38'"

the following code fails when compiling:

short a = 0;
a += (byte)1;

with: "error: incompatible types: possible lossy conversion from int to short"

a = (short)(a+1);

works fine, but the compound code should too

**Comment by rsmckinney** [comment]
Fix available in release 2020.1.39.

Thanks for reporting this!

**Comment by ggitmike** [comment]
Many thanks for looking into this so fast!

However, maybe I am an idiot, but I've changed the build.gradle file to

    compileOnly group: 'systems.manifold', name: 'manifold-preprocessor', version: '2020.1.39'

and I still get the same compiler error. Do I need to do something more?

**Comment by rsmckinney** [comment]
Ah. There was another dimension to this issue. Should finally be settled now with release 2020.1.40.  Thanks again for reporting this!

**Comment by ggitmike** [comment]
Great, it works with 2020.1.40.
Thanks a lot for fixing this to fast!
