### ISSUE TITLE
Regression: Compilation failure when using generic type parameters in records with `manifold-params`

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#716]
When using `manifold-params`, records with generic type parameters fail to compile when using generic type parameters. This is broken since version `2015.1.15`, it was working in `2015.1.14`

```java
public record TestRecord<T>(String foo, Function<? super T, String> bar) {  } // ERROR: incompatible types: bad type in conditional expression
```

**Comment by rsmckinney** [comment]
Thanks for reporting this, i have a fix ready for another release tonight.
