### ISSUE TITLE
Regression in 2026.1.1:  `sealed, non-sealed or final modifiers expected`

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#761]
My build is failing with `2026.1.1`, but was working with `2026.1.0`

```
java/awt/TextArea.java:7: error: sealed, non-sealed or final modifiers expected
public class TextArea extends java.awt.TextComponent {
       ^
```

This extensions seems to trigger the exception:
```java
package extensions.java.awt.TextArea;

import java.awt.*;

import manifold.ext.rt.api.Extension;
import manifold.ext.rt.api.Self;
import manifold.ext.rt.api.This;

@Extension
public class TextAreaExt {
    public static @Self TextArea editable(@This TextArea textArea, boolean editable) {
        textArea.setEditable(editable);
        return textArea;
    }
}
```
