### ISSUE TITLE
Structal not work in IntelliJ IDEA 2020.3.2 Ultimate

### ISSUE THREAD

**Issue by milkyway0308** [manifold-systems/manifold#249]
Hello, I'm first at manifold, and have interst and try to use it.<br>
Extension methods works perfectly, but @Structal annotation cause error at only compile (error: incompatible types), and test module give me NullPointerException while compiling. <bR>
What did I do wrong?<br><br>
#### Test class
```java
public class NameTest {
    private String name = "HELLo, WORLd!";

    @Structural
    interface Name {
        String getName();

        Name setName(String x);
    }

    public static void main(String[] args) {
        Name name = new NameTest();
        System.out.println(name.getName());
    }
}
```

#### Kotlin BuildScript
```gradle
plugins {
    id("java")
    id("maven-publish")
}

buildscript {
    repositories {
        mavenCentral()
    }
}

if (JavaVersion.current() != JavaVersion.VERSION_1_8 &&
        sourceSets["main"].allJava.files.any { it.name == "module-info.java" }) {
    tasks.withType<JavaCompile> {
        // if you DO define a module-info.java file:
        options.compilerArgs.addAll(listOf("-Xplugin:Manifold", "--module-path", classpath.asPath))
    }
} else {
    println("TEst")
    tasks.withType<JavaCompile> {
        // If you DO NOT define a module-info.java file:
        options.compilerArgs.addAll(listOf("-Xplugin:Manifold"))
        print(options.compilerArgs)
    }
}

group = "skywolf46"
version = properties["version"] as String
java {
    targetCompatibility = JavaVersion.VERSION_1_8
    sourceCompatibility = JavaVersion.VERSION_1_8
}

tasks {
    processResources {
        filesMatching("plugin.yml") {
            expand("version" to project.properties["version"])
        }
    }
}

repositories {
    mavenCentral()
    jcenter()
    maven("https://oss.sonatype.org/content/repositories/snapshots/")
    maven("https://maven.pkg.github.com/milkyway0308/CommandAnnotation") {
        credentials {
            username = properties["gpr.user"] as String
            password = properties["gpr.key"] as String
        }
    }

    maven("https://maven.pkg.github.com/milkyway0308/PlaceHolders") {
        credentials {
            username = properties["gpr.user"] as String
            password = properties["gpr.key"] as String
        }
    }

}


dependencies {
    compileOnly("org.projectlombok:lombok:1.18.16")
    annotationProcessor("org.projectlombok:lombok:1.18.16")
    implementation("systems.manifold:manifold-ext-rt:2020.1.41")
    annotationProcessor("systems.manifold:manifold-ext:2020.1.41")
    compileOnly(files("V:/API/Java/Minecraft/Bukkit/Spigot/Spigot 1.12.2.jar"))
}



publishing {
    repositories {
        maven {
            name = "Github"
            url = uri("https://maven.pkg.github.com/FUNetwork/SkywolfExtraUtility")
            credentials {
                username = properties["gpr.user"] as String
                password = properties["gpr.key"] as String
            }
        }
    }
    publications {
        create<MavenPublication>("jar") {
            from(components["java"])
            groupId = "skywolf46"
            artifactId = "exutil"
            version = properties["version"] as String
            pom {
                url.set("https://github.com/FUNetwork/SkywolfExtraUtility.git")
            }
        }
    }
}
```

**Comment by rsmckinney** [comment]
Your project is fine. You just need to cast to the structural interface:
```java
public static void main(String[] args) {
    Name name = (Name) new NameTest(); // <~~~ cast added here
    System.out.println(name.getName());
}
```
>Note, you can avoid casting with [interface extensions](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extension-interfaces).

**Comment by ghilainm** [comment]
@rsmckinney When using the intellij plugin, nothing seems to indicate that the cast is necessary. Isn't it an issue? By the way, I didn't see in the documentation any indication about this cast stuff.

**Comment by rsmckinney** [comment]
Hi @ghilainm.  Yes, the docs aren't the greatest. You can avoid casting using [extension interfaces](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extension-interfaces). 

I have some experimental code to perform a structural type check, but it's not quite ready for use.  Once that is complete, you won't have to cast at all.
